overrides:
   markdown-it@>=13.0.0 <14.1.1: ">=14.1.1"
   devalue@<=5.6.2: ">=5.6.3"
   fast-xml-parser@>=4.1.3 <5.3.6: ">=5.3.6"
   tar@<7.5.8: ">=7.5.8"
   fast-xml-parser@>=4.1.3 <5.3.5: ">=5.3.5"
   minimatch@>=5.0.0 <5.1.7: ">=5.1.7"
   minimatch@>=9.0.0 <9.0.6: ">=9.0.6"
   minimatch@>=10.0.0 <10.2.1: ">=10.2.1"
   rollup@>=4.0.0 <4.59.0: ">=4.59.0"
   minimatch@>=5.0.0 <5.1.8: ">=5.1.8"
   minimatch@>=9.0.0 <9.0.7: ">=9.0.7"
   minimatch@>=10.0.0 <10.2.3: ">=10.2.3"
   fast-xml-parser@<5.3.8: ">=5.3.8"
